// <auto-generated />
namespace GoldenTicket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GoldenTicketTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GoldenTicketTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201610071859385_GoldenTicketTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
